/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BlumebyteHrRouteImport } from './routes/blumebyte-hr'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ProjectsGhostTearsRouteImport } from './routes/projects.ghost-tears'
import { Route as ProjectsProsmeRouteImport } from './routes/projects.prosme'
import { Route as ProjectsSpaceBobRouteImport } from './routes/projects.space-bob'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BlumebyteHrRoute = BlumebyteHrRouteImport.update({
  id: '/blumebyte-hr',
  path: '/blumebyte-hr',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ProjectsGhostTearsRoute = ProjectsGhostTearsRouteImport.update({
  id: '/projects/ghost-tears',
  path: '/projects/ghost-tears',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProsmeRoute = ProjectsProsmeRouteImport.update({
  id: '/projects/prosme',
  path: '/projects/prosme',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSpaceBobRoute = ProjectsSpaceBobRouteImport.update({
  id: '/projects/space-bob',
  path: '/projects/space-bob',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/blumebyte-hr': typeof BlumebyteHrRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/ghost-tears': typeof ProjectsGhostTearsRoute
  '/projects/prosme': typeof ProjectsProsmeRoute
  '/projects/space-bob': typeof ProjectsSpaceBobRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blumebyte-hr': typeof BlumebyteHrRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/ghost-tears': typeof ProjectsGhostTearsRoute
  '/projects/prosme': typeof ProjectsProsmeRoute
  '/projects/space-bob': typeof ProjectsSpaceBobRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/blumebyte-hr': typeof BlumebyteHrRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/ghost-tears': typeof ProjectsGhostTearsRoute
  '/projects/prosme': typeof ProjectsProsmeRoute
  '/projects/space-bob': typeof ProjectsSpaceBobRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/blumebyte-hr'
    | '/contact'
    | '/faq'
    | '/portfolio'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/blog/$slug'
    | '/projects/ghost-tears'
    | '/projects/prosme'
    | '/projects/space-bob'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blumebyte-hr'
    | '/contact'
    | '/faq'
    | '/portfolio'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/blog/$slug'
    | '/projects/ghost-tears'
    | '/projects/prosme'
    | '/projects/space-bob'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/blumebyte-hr'
    | '/contact'
    | '/faq'
    | '/portfolio'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/blog/$slug'
    | '/projects/ghost-tears'
    | '/projects/prosme'
    | '/projects/space-bob'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  BlumebyteHrRoute: typeof BlumebyteHrRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  ProjectsGhostTearsRoute: typeof ProjectsGhostTearsRoute
  ProjectsProsmeRoute: typeof ProjectsProsmeRoute
  ProjectsSpaceBobRoute: typeof ProjectsSpaceBobRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blumebyte-hr': {
      id: '/blumebyte-hr'
      path: '/blumebyte-hr'
      fullPath: '/blumebyte-hr'
      preLoaderRoute: typeof BlumebyteHrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/projects/ghost-tears': {
      id: '/projects/ghost-tears'
      path: '/projects/ghost-tears'
      fullPath: '/projects/ghost-tears'
      preLoaderRoute: typeof ProjectsGhostTearsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/prosme': {
      id: '/projects/prosme'
      path: '/projects/prosme'
      fullPath: '/projects/prosme'
      preLoaderRoute: typeof ProjectsProsmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/space-bob': {
      id: '/projects/space-bob'
      path: '/projects/space-bob'
      fullPath: '/projects/space-bob'
      preLoaderRoute: typeof ProjectsSpaceBobRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  BlumebyteHrRoute: BlumebyteHrRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  ProjectsGhostTearsRoute: ProjectsGhostTearsRoute,
  ProjectsProsmeRoute: ProjectsProsmeRoute,
  ProjectsSpaceBobRoute: ProjectsSpaceBobRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
